# Generated by Django 2.1.2 on 2019-01-01 20:50

from django.db import migrations
import django_prices.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0076_auto_20181012_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='setup_fee',
            field=django_prices.models.MoneyField(currency='USD', decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
    ]
