# Generated by Django 2.1.2 on 2018-11-25 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_auto_20180719_0520'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='dob',
            field=models.DateField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='fb_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='address',
            name='gender',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='address',
            name='insta_handle',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='address',
            name='marital_status',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='address',
            name='middle_initial',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='address',
            name='occupation',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='address',
            name='referal',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='address',
            name='snapchat_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='address',
            name='suffix',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='address',
            name='title',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='address',
            name='twitter_handle',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
