# Generated by Django 2.1.2 on 2018-11-26 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_auto_20181125_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAttributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('title', models.CharField(blank=True, max_length=3)),
                ('middle_initial', models.CharField(blank=True, max_length=1)),
                ('gender', models.CharField(blank=True, max_length=1)),
                ('marital_status', models.CharField(blank=True, max_length=1)),
                ('dob', models.DateField(blank=True, max_length=8, null=True)),
                ('occupation', models.CharField(blank=True, max_length=256)),
                ('referal', models.CharField(blank=True, max_length=256)),
                ('fb_name', models.CharField(blank=True, max_length=256)),
                ('twitter_handle', models.CharField(blank=True, max_length=256)),
                ('insta_handle', models.CharField(blank=True, max_length=256)),
                ('snapchat_name', models.CharField(blank=True, max_length=256)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='address',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='address',
            name='fb_name',
        ),
        migrations.RemoveField(
            model_name='address',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='address',
            name='insta_handle',
        ),
        migrations.RemoveField(
            model_name='address',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='address',
            name='middle_initial',
        ),
        migrations.RemoveField(
            model_name='address',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='address',
            name='referal',
        ),
        migrations.RemoveField(
            model_name='address',
            name='snapchat_name',
        ),
        migrations.RemoveField(
            model_name='address',
            name='title',
        ),
        migrations.RemoveField(
            model_name='address',
            name='twitter_handle',
        ),
    ]
