# Generated by Django 2.1.2 on 2018-11-28 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_user_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='title',
        ),
    ]
