# Generated by Django 2.1.2 on 2018-12-30 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_remove_user_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='suffix',
        ),
    ]
