# Generated by Django 2.1.2 on 2018-12-30 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_remove_address_suffix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerattributes',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='customerattributes',
            name='user',
        ),
    ]
