# Generated by Django 2.1.2 on 2018-12-31 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0031_auto_20181230_1505'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerAttributes',
        ),
    ]
