# Generated by Django 2.1.2 on 2018-12-31 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0033_auto_20181231_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='referal',
            new_name='referral',
        ),
    ]
